/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { UsersUser } from "../users/User.ts";

export type SessionsSession = {
    /**
     * @type string
    */
    jwt: string;
    /**
     * @type string, date-time
    */
    expiresAt: string;
    /**
     * @type object
    */
    user: UsersUser;
};