/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ScalarsEmail } from "../scalars/Email.ts";
import type { ScalarsPassword } from "../scalars/Password.ts";

export type SessionsSessionByPasswordInput = {
    /**
     * @pattern ^(?!\s).{1,50}(?<!\s)$
     * @type string, email
    */
    email: ScalarsEmail;
    /**
     * @description Must contain at least 8 characters, one uppercase, one lowercase, one number and one special character
     * @pattern ^(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9])(?=.*[!@#$%^&*~{}_-])(?=.{8,})
     * @type string
    */
    password: ScalarsPassword;
};