/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ScalarsEmail } from "../scalars/Email.ts";
import type { ScalarsOtp } from "../scalars/Otp.ts";

export type SessionsSessionByOtpInput = {
    /**
     * @pattern ^(?!\s).{1,50}(?<!\s)$
     * @type string, email
    */
    email: ScalarsEmail;
    /**
     * @pattern ^[0-9]{6}$
     * @type string
    */
    otp: ScalarsOtp;
};