/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { UseMutationOptions, QueryClient } from "@tanstack/react-query";
import type { CreateJobApplicationMutationRequest, CreateJobApplicationMutationResponse } from "../../ts/CreateJobApplication.ts";
import { useMutation } from "@tanstack/react-query";

export const createJobApplicationMutationKey = () => [{ url: '/jobApplications' }] as const

export type CreateJobApplicationMutationKey = ReturnType<typeof createJobApplicationMutationKey>

/**
 * @description createJobApplication
 * {@link /jobApplications}
 */
export async function createJobApplication(data: CreateJobApplicationMutationRequest, config: Partial<RequestConfig<CreateJobApplicationMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<CreateJobApplicationMutationResponse, ResponseErrorConfig<Error>, CreateJobApplicationMutationRequest>({ method : "POST", url : `/jobApplications`, data : requestData, ... requestConfig })  
  return res.data
}

/**
 * @description createJobApplication
 * {@link /jobApplications}
 */
export function useCreateJobApplication<TContext>(options: 
{
  mutation?: UseMutationOptions<CreateJobApplicationMutationResponse, ResponseErrorConfig<Error>, {data: CreateJobApplicationMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<CreateJobApplicationMutationRequest>> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? createJobApplicationMutationKey()

  return useMutation<CreateJobApplicationMutationResponse, ResponseErrorConfig<Error>, {data: CreateJobApplicationMutationRequest}, TContext>({
    mutationFn: async({ data }) => {
      return createJobApplication(data, config)
    },
    mutationKey,
    ...mutationOptions
  }, queryClient)
}