/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import type { ListJobApplicationsQueryResponse, ListJobApplicationsQueryParams } from "../../ts/ListJobApplications.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const listJobApplicationsQueryKey = (params?: ListJobApplicationsQueryParams) => [{ url: '/jobApplications' }, ...(params ? [params] : [])] as const

export type ListJobApplicationsQueryKey = ReturnType<typeof listJobApplicationsQueryKey>

/**
 * @description listJobApplications
 * {@link /jobApplications}
 */
export async function listJobApplications(params?: ListJobApplicationsQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<ListJobApplicationsQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : `/jobApplications`, params, ... requestConfig })  
  return res.data
}

export function listJobApplicationsQueryOptions(params?: ListJobApplicationsQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = listJobApplicationsQueryKey(params)
  return queryOptions<ListJobApplicationsQueryResponse, ResponseErrorConfig<Error>, ListJobApplicationsQueryResponse, typeof queryKey>({
 
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return listJobApplications(params, config)
   },
  })
}

/**
 * @description listJobApplications
 * {@link /jobApplications}
 */
export function useListJobApplications<TData = ListJobApplicationsQueryResponse, TQueryData = ListJobApplicationsQueryResponse, TQueryKey extends QueryKey = ListJobApplicationsQueryKey>(params?: ListJobApplicationsQueryParams, options: 
{
  query?: Partial<QueryObserverOptions<ListJobApplicationsQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? listJobApplicationsQueryKey(params)

  const query = useQuery({
   ...listJobApplicationsQueryOptions(params, config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}