/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


/**
 * @description Must contain at least 8 characters, one uppercase, one lowercase, one number and one special character
 * @minLength 1
 * @maxLength 50
 * @pattern ^(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9])(?=.*[!@#$%^&*~{}_-])(?=.{8,})
*/
export type ScalarsPassword = string;