/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { UseMutationOptions, QueryClient } from "@tanstack/react-query";
import type { ReplaceMyPasswordMutationRequest, ReplaceMyPasswordMutationResponse, ReplaceMyPassword400, ReplaceMyPassword500 } from "../../ts/ReplaceMyPassword.ts";
import { useMutation } from "@tanstack/react-query";

export const replaceMyPasswordMutationKey = () => [{ url: '/users/@me/password' }] as const

export type ReplaceMyPasswordMutationKey = ReturnType<typeof replaceMyPasswordMutationKey>

/**
 * @description replaceMyPassword
 * {@link /users/@me/password}
 */
export async function replaceMyPassword(data: ReplaceMyPasswordMutationRequest, config: Partial<RequestConfig<ReplaceMyPasswordMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<ReplaceMyPasswordMutationResponse, ResponseErrorConfig<ReplaceMyPassword400 | ReplaceMyPassword500>, ReplaceMyPasswordMutationRequest>({ method : "PUT", url : `/users/@me/password`, data : requestData, ... requestConfig })  
  return res.data
}

/**
 * @description replaceMyPassword
 * {@link /users/@me/password}
 */
export function useReplaceMyPassword<TContext>(options: 
{
  mutation?: UseMutationOptions<ReplaceMyPasswordMutationResponse, ResponseErrorConfig<ReplaceMyPassword400 | ReplaceMyPassword500>, {data: ReplaceMyPasswordMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<ReplaceMyPasswordMutationRequest>> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? replaceMyPasswordMutationKey()

  return useMutation<ReplaceMyPasswordMutationResponse, ResponseErrorConfig<ReplaceMyPassword400 | ReplaceMyPassword500>, {data: ReplaceMyPasswordMutationRequest}, TContext>({
    mutationFn: async({ data }) => {
      return replaceMyPassword(data, config)
    },
    mutationKey,
    ...mutationOptions
  }, queryClient)
}