/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { UseMutationOptions, QueryClient } from "@tanstack/react-query";
import type { CreateSessionByPasswordMutationRequest, CreateSessionByPasswordMutationResponse, CreateSessionByPassword400, CreateSessionByPassword401, CreateSessionByPassword404, CreateSessionByPassword500 } from "../../ts/CreateSessionByPassword.ts";
import { useMutation } from "@tanstack/react-query";

export const createSessionByPasswordMutationKey = () => [{ url: '/sessions/@password' }] as const

export type CreateSessionByPasswordMutationKey = ReturnType<typeof createSessionByPasswordMutationKey>

/**
 * @description createSessionByPassword
 * {@link /sessions/@password}
 */
export async function createSessionByPassword(data: CreateSessionByPasswordMutationRequest, config: Partial<RequestConfig<CreateSessionByPasswordMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<CreateSessionByPasswordMutationResponse, ResponseErrorConfig<CreateSessionByPassword400 | CreateSessionByPassword401 | CreateSessionByPassword404 | CreateSessionByPassword500>, CreateSessionByPasswordMutationRequest>({ method : "POST", url : `/sessions/@password`, data : requestData, ... requestConfig })  
  return res.data
}

/**
 * @description createSessionByPassword
 * {@link /sessions/@password}
 */
export function useCreateSessionByPassword<TContext>(options: 
{
  mutation?: UseMutationOptions<CreateSessionByPasswordMutationResponse, ResponseErrorConfig<CreateSessionByPassword400 | CreateSessionByPassword401 | CreateSessionByPassword404 | CreateSessionByPassword500>, {data: CreateSessionByPasswordMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<CreateSessionByPasswordMutationRequest>> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? createSessionByPasswordMutationKey()

  return useMutation<CreateSessionByPasswordMutationResponse, ResponseErrorConfig<CreateSessionByPassword400 | CreateSessionByPassword401 | CreateSessionByPassword404 | CreateSessionByPassword500>, {data: CreateSessionByPasswordMutationRequest}, TContext>({
    mutationFn: async({ data }) => {
      return createSessionByPassword(data, config)
    },
    mutationKey,
    ...mutationOptions
  }, queryClient)
}