/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export const enumsEnabledStateEnum = {
    "ENABLED": "ENABLED",
    "DISABLED": "DISABLED"
} as const;

export type EnumsEnabledStateEnum = (typeof enumsEnabledStateEnum)[keyof typeof enumsEnabledStateEnum];

export type EnumsEnabledState = EnumsEnabledStateEnum;