/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ScalarsId } from "../scalars/Id.ts";

export type NotificationsNotificationUpdate = {
    /**
     * @type array
    */
    readIds: ScalarsId[];
    /**
     * @type array
    */
    unreadIds: ScalarsId[];
};