/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { NotificationsReadState } from "./ReadState.ts";
import type { ScalarsDatetime } from "../scalars/Datetime.ts";
import type { ScalarsId } from "../scalars/Id.ts";
import type { ScalarsStr50 } from "../scalars/Str50.ts";
import type { ScalarsStr100 } from "../scalars/Str100.ts";

export type NotificationsNotification = {
    /**
     * @description Must be a natural number
     * @type integer
    */
    id: ScalarsId;
    userId: (ScalarsId | null);
    /**
     * @pattern ^(?!\s).{1,50}(?<!\s)$
     * @type string
    */
    title: ScalarsStr50;
    /**
     * @pattern ^(?!\s).{1,100}(?<!\s)$
     * @type string
    */
    message: ScalarsStr100;
    /**
     * @type string
    */
    readState: NotificationsReadState;
    /**
     * @description Must be a valid ISO 8601 string. No timezone offsets are allowed
     * @type string, date-time
    */
    createdAt: ScalarsDatetime;
    /**
     * @description Must be a valid ISO 8601 string. No timezone offsets are allowed
     * @type string, date-time
    */
    validAt: ScalarsDatetime;
};