/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export const notificationsReadStateEnum = {
    "READ": "READ",
    "UNREAD": "UNREAD"
} as const;

export type NotificationsReadStateEnum = (typeof notificationsReadStateEnum)[keyof typeof notificationsReadStateEnum];

export type NotificationsReadState = NotificationsReadStateEnum;