/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export const jobPostingsJobTypeEnum = {
    "FULL_TIME": "FULL_TIME",
    "PART_TIME": "PART_TIME",
    "CONTRACT": "CONTRACT",
    "INTERNSHIP": "INTERNSHIP"
} as const;

export type JobPostingsJobTypeEnum = (typeof jobPostingsJobTypeEnum)[keyof typeof jobPostingsJobTypeEnum];

export type JobPostingsJobType = JobPostingsJobTypeEnum;