/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export const jobPostingsJobWorkModeEnum = {
    "ON_SITE": "ON_SITE",
    "REMOTE": "REMOTE",
    "HYBRID": "HYBRID"
} as const;

export type JobPostingsJobWorkModeEnum = (typeof jobPostingsJobWorkModeEnum)[keyof typeof jobPostingsJobWorkModeEnum];

export type JobPostingsJobWorkMode = JobPostingsJobWorkModeEnum;