/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export const jobPostingsProcessingStateEnum = {
    "PENDING": "PENDING",
    "OPEN": "OPEN",
    "CLOSED": "CLOSED",
    "ARCHIVED": "ARCHIVED"
} as const;

export type JobPostingsProcessingStateEnum = (typeof jobPostingsProcessingStateEnum)[keyof typeof jobPostingsProcessingStateEnum];

export type JobPostingsProcessingState = JobPostingsProcessingStateEnum;