/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ScalarsStr50 } from "../scalars/Str50.ts";

/**
 * @description The template for omitting properties.
*/
export type JobCategoriesJobCategoryInput = {
    /**
     * @pattern ^(?!\s).{1,50}(?<!\s)$
     * @type string
    */
    name: ScalarsStr50;
};