/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ScalarsId } from "../scalars/Id.ts";
import type { ScalarsStr50 } from "../scalars/Str50.ts";

/**
 * @description The template for omitting properties.
*/
export type JobCategoriesJobPositionInput = {
    /**
     * @description Must be a natural number
     * @type integer
    */
    categoryId: ScalarsId;
    /**
     * @pattern ^(?!\s).{1,50}(?<!\s)$
     * @type string
    */
    name: ScalarsStr50;
};