/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import type { ListJobPositionsQueryResponse, ListJobPositionsQueryParams, ListJobPositions400, ListJobPositions404, ListJobPositions500 } from "../../ts/ListJobPositions.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const listJobPositionsSuspenseQueryKey = (params?: ListJobPositionsQueryParams) => [{ url: '/jobPositions' }, ...(params ? [params] : [])] as const

export type ListJobPositionsSuspenseQueryKey = ReturnType<typeof listJobPositionsSuspenseQueryKey>

/**
 * @description listJobPositions
 * {@link /jobPositions}
 */
export async function listJobPositionsSuspense(params?: ListJobPositionsQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<ListJobPositionsQueryResponse, ResponseErrorConfig<ListJobPositions400 | ListJobPositions404 | ListJobPositions500>, unknown>({ method : "GET", url : `/jobPositions`, params, ... requestConfig })  
  return res.data
}

export function listJobPositionsSuspenseQueryOptions(params?: ListJobPositionsQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = listJobPositionsSuspenseQueryKey(params)
  return queryOptions<ListJobPositionsQueryResponse, ResponseErrorConfig<ListJobPositions400 | ListJobPositions404 | ListJobPositions500>, ListJobPositionsQueryResponse, typeof queryKey>({
 
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return listJobPositionsSuspense(params, config)
   },
  })
}

/**
 * @description listJobPositions
 * {@link /jobPositions}
 */
export function useListJobPositionsSuspense<TData = ListJobPositionsQueryResponse, TQueryKey extends QueryKey = ListJobPositionsSuspenseQueryKey>(params?: ListJobPositionsQueryParams, options: 
{
  query?: Partial<UseSuspenseQueryOptions<ListJobPositionsQueryResponse, ResponseErrorConfig<ListJobPositions400 | ListJobPositions404 | ListJobPositions500>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? listJobPositionsSuspenseQueryKey(params)

  const query = useSuspenseQuery({
   ...listJobPositionsSuspenseQueryOptions(params, config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<ListJobPositions400 | ListJobPositions404 | ListJobPositions500>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}