/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import type { ListJobCategoriesQueryResponse, ListJobCategoriesQueryParams, ListJobCategories400, ListJobCategories404, ListJobCategories500 } from "../../ts/ListJobCategories.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const listJobCategoriesSuspenseQueryKey = (params?: ListJobCategoriesQueryParams) => [{ url: '/jobCategories' }, ...(params ? [params] : [])] as const

export type ListJobCategoriesSuspenseQueryKey = ReturnType<typeof listJobCategoriesSuspenseQueryKey>

/**
 * @description listJobCategories
 * {@link /jobCategories}
 */
export async function listJobCategoriesSuspense(params?: ListJobCategoriesQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<ListJobCategoriesQueryResponse, ResponseErrorConfig<ListJobCategories400 | ListJobCategories404 | ListJobCategories500>, unknown>({ method : "GET", url : `/jobCategories`, params, ... requestConfig })  
  return res.data
}

export function listJobCategoriesSuspenseQueryOptions(params?: ListJobCategoriesQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = listJobCategoriesSuspenseQueryKey(params)
  return queryOptions<ListJobCategoriesQueryResponse, ResponseErrorConfig<ListJobCategories400 | ListJobCategories404 | ListJobCategories500>, ListJobCategoriesQueryResponse, typeof queryKey>({
 
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return listJobCategoriesSuspense(params, config)
   },
  })
}

/**
 * @description listJobCategories
 * {@link /jobCategories}
 */
export function useListJobCategoriesSuspense<TData = ListJobCategoriesQueryResponse, TQueryKey extends QueryKey = ListJobCategoriesSuspenseQueryKey>(params?: ListJobCategoriesQueryParams, options: 
{
  query?: Partial<UseSuspenseQueryOptions<ListJobCategoriesQueryResponse, ResponseErrorConfig<ListJobCategories400 | ListJobCategories404 | ListJobCategories500>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? listJobCategoriesSuspenseQueryKey(params)

  const query = useSuspenseQuery({
   ...listJobCategoriesSuspenseQueryOptions(params, config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<ListJobCategories400 | ListJobCategories404 | ListJobCategories500>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}