/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { UploadsUpload } from "./uploads/Upload.ts";
import type { UploadsUploadCategory } from "./uploads/UploadCategory.ts";

export type CreateUploadQueryParams = {
    /**
     * @type string
    */
    category: UploadsUploadCategory;
};

/**
 * @description The request has succeeded and a new resource has been created as a result.
*/
export type CreateUpload201 = UploadsUpload;

/**
 * @description The server could not understand the request due to invalid syntax.
*/
export type CreateUpload400 = {
    /**
     * @type object
    */
    message: {
        /**
         * @type string
        */
        ENGLISH: string;
        /**
         * @type string
        */
        SINHALA: string;
        /**
         * @type string
        */
        TAMIL: string;
    };
};

/**
 * @description The server cannot find the requested resource.
*/
export type CreateUpload404 = {
    /**
     * @type object
    */
    message: {
        /**
         * @type string
        */
        ENGLISH: string;
        /**
         * @type string
        */
        SINHALA: string;
        /**
         * @type string
        */
        TAMIL: string;
    };
};

/**
 * @description Client error
*/
export type CreateUpload413 = {
    /**
     * @type object
    */
    message: {
        /**
         * @type string
        */
        ENGLISH: string;
        /**
         * @type string
        */
        SINHALA: string;
        /**
         * @type string
        */
        TAMIL: string;
    };
};

/**
 * @description Client error
*/
export type CreateUpload415 = {
    /**
     * @type object
    */
    message: {
        /**
         * @type string
        */
        ENGLISH: string;
        /**
         * @type string
        */
        SINHALA: string;
        /**
         * @type string
        */
        TAMIL: string;
    };
};

/**
 * @description Server error
*/
export type CreateUpload500 = {
    /**
     * @type object
    */
    message: {
        /**
         * @type string
        */
        ENGLISH: string;
        /**
         * @type string
        */
        SINHALA: string;
        /**
         * @type string
        */
        TAMIL: string;
    };
};

export type CreateUploadMutationRequest = {
    file: any;
};

export type CreateUploadMutationResponse = CreateUpload201;

export type CreateUploadMutation = {
    Response: CreateUpload201;
    Request: CreateUploadMutationRequest;
    QueryParams: CreateUploadQueryParams;
    Errors: CreateUpload400 | CreateUpload404 | CreateUpload413 | CreateUpload415 | CreateUpload500;
};