/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { JobPostingsJobPosting } from "./jobPostings/JobPosting.ts";
import type { JobPostingsJobPostingInput } from "./jobPostings/JobPostingInput.ts";

/**
 * @description The request has succeeded and a new resource has been created as a result.
*/
export type CreateJobPosting201 = JobPostingsJobPosting;

export type CreateJobPostingMutationRequest = JobPostingsJobPostingInput;

export type CreateJobPostingMutationResponse = CreateJobPosting201;

export type CreateJobPostingMutation = {
    Response: CreateJobPosting201;
    Request: CreateJobPostingMutationRequest;
    Errors: any;
};