/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { SessionsSession } from "./sessions/Session.ts";
import type { SessionsSessionByPasswordInput } from "./sessions/SessionByPasswordInput.ts";

/**
 * @description The request has succeeded and a new resource has been created as a result.
*/
export type CreateSessionByPassword201 = SessionsSession;

/**
 * @description The server could not understand the request due to invalid syntax.
*/
export type CreateSessionByPassword400 = {
    /**
     * @type object
    */
    message: {
        /**
         * @type string
        */
        ENGLISH: string;
        /**
         * @type string
        */
        SINHALA: string;
        /**
         * @type string
        */
        TAMIL: string;
    };
};

/**
 * @description Access is unauthorized.
*/
export type CreateSessionByPassword401 = {
    /**
     * @type object
    */
    message: {
        /**
         * @type string
        */
        ENGLISH: string;
        /**
         * @type string
        */
        SINHALA: string;
        /**
         * @type string
        */
        TAMIL: string;
    };
};

/**
 * @description The server cannot find the requested resource.
*/
export type CreateSessionByPassword404 = {
    /**
     * @type object
    */
    message: {
        /**
         * @type string
        */
        ENGLISH: string;
        /**
         * @type string
        */
        SINHALA: string;
        /**
         * @type string
        */
        TAMIL: string;
    };
};

/**
 * @description Server error
*/
export type CreateSessionByPassword500 = {
    /**
     * @type object
    */
    message: {
        /**
         * @type string
        */
        ENGLISH: string;
        /**
         * @type string
        */
        SINHALA: string;
        /**
         * @type string
        */
        TAMIL: string;
    };
};

export type CreateSessionByPasswordMutationRequest = SessionsSessionByPasswordInput;

export type CreateSessionByPasswordMutationResponse = CreateSessionByPassword201;

export type CreateSessionByPasswordMutation = {
    Response: CreateSessionByPassword201;
    Request: CreateSessionByPasswordMutationRequest;
    Errors: CreateSessionByPassword400 | CreateSessionByPassword401 | CreateSessionByPassword404 | CreateSessionByPassword500;
};