/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { JobCategoriesJobCategory } from "./jobCategories/JobCategory.ts";
import type { JobCategoriesJobCategoryInput } from "./jobCategories/JobCategoryInput.ts";

/**
 * @description The request has succeeded and a new resource has been created as a result.
*/
export type CreateJobCategory201 = JobCategoriesJobCategory;

/**
 * @description The server could not understand the request due to invalid syntax.
*/
export type CreateJobCategory400 = {
    /**
     * @type object
    */
    message: {
        /**
         * @type string
        */
        ENGLISH: string;
        /**
         * @type string
        */
        SINHALA: string;
        /**
         * @type string
        */
        TAMIL: string;
    };
};

/**
 * @description The server cannot find the requested resource.
*/
export type CreateJobCategory404 = {
    /**
     * @type object
    */
    message: {
        /**
         * @type string
        */
        ENGLISH: string;
        /**
         * @type string
        */
        SINHALA: string;
        /**
         * @type string
        */
        TAMIL: string;
    };
};

/**
 * @description Server error
*/
export type CreateJobCategory500 = {
    /**
     * @type object
    */
    message: {
        /**
         * @type string
        */
        ENGLISH: string;
        /**
         * @type string
        */
        SINHALA: string;
        /**
         * @type string
        */
        TAMIL: string;
    };
};

export type CreateJobCategoryMutationRequest = JobCategoriesJobCategoryInput;

export type CreateJobCategoryMutationResponse = CreateJobCategory201;

export type CreateJobCategoryMutation = {
    Response: CreateJobCategory201;
    Request: CreateJobCategoryMutationRequest;
    Errors: CreateJobCategory400 | CreateJobCategory404 | CreateJobCategory500;
};