/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { JobApplicationsJobApplication } from "./jobApplications/JobApplication.ts";
import type { JobApplicationsJobApplicationInput } from "./jobApplications/JobApplicationInput.ts";

/**
 * @description The request has succeeded and a new resource has been created as a result.
*/
export type CreateJobApplication201 = JobApplicationsJobApplication;

export type CreateJobApplicationMutationRequest = JobApplicationsJobApplicationInput;

export type CreateJobApplicationMutationResponse = CreateJobApplication201;

export type CreateJobApplicationMutation = {
    Response: CreateJobApplication201;
    Request: CreateJobApplicationMutationRequest;
    Errors: any;
};