/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { JobCategoriesJobPosition } from "./jobCategories/JobPosition.ts";
import type { JobCategoriesJobPositionInput } from "./jobCategories/JobPositionInput.ts";

/**
 * @description The request has succeeded and a new resource has been created as a result.
*/
export type CreateJobPosition201 = JobCategoriesJobPosition;

/**
 * @description The server could not understand the request due to invalid syntax.
*/
export type CreateJobPosition400 = {
    /**
     * @type object
    */
    message: {
        /**
         * @type string
        */
        ENGLISH: string;
        /**
         * @type string
        */
        SINHALA: string;
        /**
         * @type string
        */
        TAMIL: string;
    };
};

/**
 * @description The server cannot find the requested resource.
*/
export type CreateJobPosition404 = {
    /**
     * @type object
    */
    message: {
        /**
         * @type string
        */
        ENGLISH: string;
        /**
         * @type string
        */
        SINHALA: string;
        /**
         * @type string
        */
        TAMIL: string;
    };
};

/**
 * @description Server error
*/
export type CreateJobPosition500 = {
    /**
     * @type object
    */
    message: {
        /**
         * @type string
        */
        ENGLISH: string;
        /**
         * @type string
        */
        SINHALA: string;
        /**
         * @type string
        */
        TAMIL: string;
    };
};

export type CreateJobPositionMutationRequest = JobCategoriesJobPositionInput;

export type CreateJobPositionMutationResponse = CreateJobPosition201;

export type CreateJobPositionMutation = {
    Response: CreateJobPosition201;
    Request: CreateJobPositionMutationRequest;
    Errors: CreateJobPosition400 | CreateJobPosition404 | CreateJobPosition500;
};