/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { UsersUser } from "./users/User.ts";
import type { UsersUserInput } from "./users/UserInput.ts";

/**
 * @description The request has succeeded and a new resource has been created as a result.
*/
export type CreateUser201 = UsersUser;

/**
 * @description The server could not understand the request due to invalid syntax.
*/
export type CreateUser400 = {
    /**
     * @type object
    */
    message: {
        /**
         * @type string
        */
        ENGLISH: string;
        /**
         * @type string
        */
        SINHALA: string;
        /**
         * @type string
        */
        TAMIL: string;
    };
};

/**
 * @description The server cannot find the requested resource.
*/
export type CreateUser404 = {
    /**
     * @type object
    */
    message: {
        /**
         * @type string
        */
        ENGLISH: string;
        /**
         * @type string
        */
        SINHALA: string;
        /**
         * @type string
        */
        TAMIL: string;
    };
};

/**
 * @description The request conflicts with the current state of the server.
*/
export type CreateUser409 = {
    /**
     * @type object
    */
    message: {
        /**
         * @type string
        */
        ENGLISH: string;
        /**
         * @type string
        */
        SINHALA: string;
        /**
         * @type string
        */
        TAMIL: string;
    };
};

/**
 * @description Server error
*/
export type CreateUser500 = {
    /**
     * @type object
    */
    message: {
        /**
         * @type string
        */
        ENGLISH: string;
        /**
         * @type string
        */
        SINHALA: string;
        /**
         * @type string
        */
        TAMIL: string;
    };
};

export type CreateUserMutationRequest = UsersUserInput;

export type CreateUserMutationResponse = CreateUser201;

export type CreateUserMutation = {
    Response: CreateUser201;
    Request: CreateUserMutationRequest;
    Errors: CreateUser400 | CreateUser404 | CreateUser409 | CreateUser500;
};