/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type FetchUploadPathParams = {
    /**
     * @type string
    */
    staticPath: string;
};

/**
 * @description The request has succeeded.
*/
export type FetchUpload200 = any;

/**
 * @description The server could not understand the request due to invalid syntax.
*/
export type FetchUpload400 = {
    /**
     * @type object
    */
    message: {
        /**
         * @type string
        */
        ENGLISH: string;
        /**
         * @type string
        */
        SINHALA: string;
        /**
         * @type string
        */
        TAMIL: string;
    };
};

/**
 * @description The server cannot find the requested resource.
*/
export type FetchUpload404 = {
    /**
     * @type object
    */
    message: {
        /**
         * @type string
        */
        ENGLISH: string;
        /**
         * @type string
        */
        SINHALA: string;
        /**
         * @type string
        */
        TAMIL: string;
    };
};

/**
 * @description Server error
*/
export type FetchUpload500 = {
    /**
     * @type object
    */
    message: {
        /**
         * @type string
        */
        ENGLISH: string;
        /**
         * @type string
        */
        SINHALA: string;
        /**
         * @type string
        */
        TAMIL: string;
    };
};

export type FetchUploadQueryResponse = FetchUpload200;

export type FetchUploadQuery = {
    Response: FetchUpload200;
    PathParams: FetchUploadPathParams;
    Errors: FetchUpload400 | FetchUpload404 | FetchUpload500;
};