/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { JobCategoriesJobPosition } from "./jobCategories/JobPosition.ts";
import type { ScalarsId } from "./scalars/Id.ts";

export type ListJobPositionsQueryParams = {
    /**
     * @minLength 1
     * @maxLength 50
     * @default 50
     * @type integer | undefined
    */
    pageSize?: number;
    /**
     * @minLength 0
     * @type integer | undefined
    */
    page?: number;
    /**
     * @description Must be a natural number
     * @type integer | undefined
    */
    categoryId?: ScalarsId;
};

/**
 * @description The request has succeeded.
*/
export type ListJobPositions200 = {
    /**
     * @description Will be calculated only if the \'page\' parameter is explicitly set to 0
     * @type integer | undefined
    */
    totalCount?: number;
    /**
     * @type array
    */
    data: JobCategoriesJobPosition[];
};

/**
 * @description The server could not understand the request due to invalid syntax.
*/
export type ListJobPositions400 = {
    /**
     * @type object
    */
    message: {
        /**
         * @type string
        */
        ENGLISH: string;
        /**
         * @type string
        */
        SINHALA: string;
        /**
         * @type string
        */
        TAMIL: string;
    };
};

/**
 * @description The server cannot find the requested resource.
*/
export type ListJobPositions404 = {
    /**
     * @type object
    */
    message: {
        /**
         * @type string
        */
        ENGLISH: string;
        /**
         * @type string
        */
        SINHALA: string;
        /**
         * @type string
        */
        TAMIL: string;
    };
};

/**
 * @description Server error
*/
export type ListJobPositions500 = {
    /**
     * @type object
    */
    message: {
        /**
         * @type string
        */
        ENGLISH: string;
        /**
         * @type string
        */
        SINHALA: string;
        /**
         * @type string
        */
        TAMIL: string;
    };
};

export type ListJobPositionsQueryResponse = ListJobPositions200;

export type ListJobPositionsQuery = {
    Response: ListJobPositions200;
    QueryParams: ListJobPositionsQueryParams;
    Errors: ListJobPositions400 | ListJobPositions404 | ListJobPositions500;
};