/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { JobCategoriesJobCategory } from "./jobCategories/JobCategory.ts";

export type ListJobCategoriesQueryParams = {
    /**
     * @minLength 1
     * @maxLength 50
     * @default 50
     * @type integer | undefined
    */
    pageSize?: number;
    /**
     * @minLength 0
     * @type integer | undefined
    */
    page?: number;
};

/**
 * @description The request has succeeded.
*/
export type ListJobCategories200 = {
    /**
     * @description Will be calculated only if the \'page\' parameter is explicitly set to 0
     * @type integer | undefined
    */
    totalCount?: number;
    /**
     * @type array
    */
    data: JobCategoriesJobCategory[];
};

/**
 * @description The server could not understand the request due to invalid syntax.
*/
export type ListJobCategories400 = {
    /**
     * @type object
    */
    message: {
        /**
         * @type string
        */
        ENGLISH: string;
        /**
         * @type string
        */
        SINHALA: string;
        /**
         * @type string
        */
        TAMIL: string;
    };
};

/**
 * @description The server cannot find the requested resource.
*/
export type ListJobCategories404 = {
    /**
     * @type object
    */
    message: {
        /**
         * @type string
        */
        ENGLISH: string;
        /**
         * @type string
        */
        SINHALA: string;
        /**
         * @type string
        */
        TAMIL: string;
    };
};

/**
 * @description Server error
*/
export type ListJobCategories500 = {
    /**
     * @type object
    */
    message: {
        /**
         * @type string
        */
        ENGLISH: string;
        /**
         * @type string
        */
        SINHALA: string;
        /**
         * @type string
        */
        TAMIL: string;
    };
};

export type ListJobCategoriesQueryResponse = ListJobCategories200;

export type ListJobCategoriesQuery = {
    Response: ListJobCategories200;
    QueryParams: ListJobCategoriesQueryParams;
    Errors: ListJobCategories400 | ListJobCategories404 | ListJobCategories500;
};