/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { NotificationsNotificationUpdate } from "./notifications/NotificationUpdate.ts";

/**
 * @description There is no content to send for this request, but the headers may be useful.
*/
export type ReplaceNotifications204 = any;

export type ReplaceNotificationsMutationRequest = {
    /**
     * @type object
    */
    data: NotificationsNotificationUpdate;
};

export type ReplaceNotificationsMutationResponse = ReplaceNotifications204;

export type ReplaceNotificationsMutation = {
    Response: ReplaceNotifications204;
    Request: ReplaceNotificationsMutationRequest;
    Errors: any;
};