/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ScalarsId } from "./scalars/Id.ts";
import type { StructsPasswordInput } from "./structs/PasswordInput.ts";

export type ReplacePasswordPathParams = {
    /**
     * @description Must be a natural number
     * @type integer
    */
    id: ScalarsId;
};

/**
 * @description There is no content to send for this request, but the headers may be useful.
*/
export type ReplacePassword204 = any;

export type ReplacePasswordMutationRequest = StructsPasswordInput;

export type ReplacePasswordMutationResponse = ReplacePassword204;

export type ReplacePasswordMutation = {
    Response: ReplacePassword204;
    Request: ReplacePasswordMutationRequest;
    PathParams: ReplacePasswordPathParams;
    Errors: any;
};