/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ScalarsPassword } from "./scalars/Password.ts";

/**
 * @description There is no content to send for this request, but the headers may be useful.
*/
export type ReplaceMyPassword204 = any;

/**
 * @description The server could not understand the request due to invalid syntax.
*/
export type ReplaceMyPassword400 = ({
    /**
     * @type object
    */
    message: {
        /**
         * @type string
        */
        ENGLISH: string;
        /**
         * @type string
        */
        SINHALA: string;
        /**
         * @type string
        */
        TAMIL: string;
    };
} | {
    /**
     * @type object
    */
    message: {
        /**
         * @type string
        */
        ENGLISH: string;
        /**
         * @type string
        */
        SINHALA: string;
        /**
         * @type string
        */
        TAMIL: string;
    };
});

/**
 * @description Server error
*/
export type ReplaceMyPassword500 = {
    /**
     * @type object
    */
    message: {
        /**
         * @type string
        */
        ENGLISH: string;
        /**
         * @type string
        */
        SINHALA: string;
        /**
         * @type string
        */
        TAMIL: string;
    };
};

export type ReplaceMyPasswordMutationRequest = {
    /**
     * @description Must contain at least 8 characters, one uppercase, one lowercase, one number and one special character
     * @pattern ^(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9])(?=.*[!@#$%^&*~{}_-])(?=.{8,})
     * @type string
    */
    oldPassword: ScalarsPassword;
    /**
     * @description Must contain at least 8 characters, one uppercase, one lowercase, one number and one special character
     * @pattern ^(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9])(?=.*[!@#$%^&*~{}_-])(?=.{8,})
     * @type string
    */
    newPassword: ScalarsPassword;
};

export type ReplaceMyPasswordMutationResponse = ReplaceMyPassword204;

export type ReplaceMyPasswordMutation = {
    Response: ReplaceMyPassword204;
    Request: ReplaceMyPasswordMutationRequest;
    Errors: ReplaceMyPassword400 | ReplaceMyPassword500;
};