/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { JobApplicationsJobApplication } from "./jobApplications/JobApplication.ts";
import type { JobApplicationsJobApplicationInput } from "./jobApplications/JobApplicationInput.ts";
import type { ScalarsId } from "./scalars/Id.ts";

export type ReplaceJobApplicationPathParams = {
    /**
     * @description Must be a natural number
     * @type integer
    */
    id: ScalarsId;
};

/**
 * @description The request has succeeded and a new resource has been created as a result.
*/
export type ReplaceJobApplication201 = JobApplicationsJobApplication;

export type ReplaceJobApplicationMutationRequest = JobApplicationsJobApplicationInput;

export type ReplaceJobApplicationMutationResponse = ReplaceJobApplication201;

export type ReplaceJobApplicationMutation = {
    Response: ReplaceJobApplication201;
    Request: ReplaceJobApplicationMutationRequest;
    PathParams: ReplaceJobApplicationPathParams;
    Errors: any;
};