/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { JobPostingsJobPosting } from "./jobPostings/JobPosting.ts";
import type { JobPostingsJobPostingInput } from "./jobPostings/JobPostingInput.ts";
import type { ScalarsId } from "./scalars/Id.ts";

export type ReplaceJobPostingPathParams = {
    /**
     * @description Must be a natural number
     * @type integer
    */
    id: ScalarsId;
};

/**
 * @description The request has succeeded and a new resource has been created as a result.
*/
export type ReplaceJobPosting201 = JobPostingsJobPosting;

export type ReplaceJobPostingMutationRequest = JobPostingsJobPostingInput;

export type ReplaceJobPostingMutationResponse = ReplaceJobPosting201;

export type ReplaceJobPostingMutation = {
    Response: ReplaceJobPosting201;
    Request: ReplaceJobPostingMutationRequest;
    PathParams: ReplaceJobPostingPathParams;
    Errors: any;
};