/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { EnumsEnabledState } from "../enums/EnabledState.ts";
import type { ScalarsEmail } from "../scalars/Email.ts";
import type { ScalarsId } from "../scalars/Id.ts";
import type { ScalarsPassword } from "../scalars/Password.ts";
import type { ScalarsStr100 } from "../scalars/Str100.ts";

export type UsersUserInput = {
    /**
     * @pattern ^(?!\s).{1,50}(?<!\s)$
     * @type string, email
    */
    email: ScalarsEmail;
    /**
     * @pattern ^(?!\s).{1,100}(?<!\s)$
     * @type string
    */
    name: ScalarsStr100;
    /**
     * @type string
    */
    description: string;
    /**
     * @description Must be a natural number
     * @type integer
    */
    roleId: ScalarsId;
    /**
     * @type string
    */
    enabledState: EnumsEnabledState;
    /**
     * @description Must contain at least 8 characters, one uppercase, one lowercase, one number and one special character
     * @pattern ^(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9])(?=.*[!@#$%^&*~{}_-])(?=.{8,})
     * @type string
    */
    password: ScalarsPassword;
};