/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { EnumsEnabledState } from "../enums/EnabledState.ts";
import type { ScalarsEmail } from "../scalars/Email.ts";
import type { ScalarsId } from "../scalars/Id.ts";
import type { ScalarsStr100 } from "../scalars/Str100.ts";
import type { ScalarsStr1000 } from "../scalars/Str1000.ts";

export type UsersUser = {
    /**
     * @description Must be a natural number
     * @type integer
    */
    id: ScalarsId;
    /**
     * @pattern ^(?!\s).{1,50}(?<!\s)$
     * @type string, email
    */
    email: ScalarsEmail;
    /**
     * @pattern ^(?!\s).{1,100}(?<!\s)$
     * @type string
    */
    name: ScalarsStr100;
    /**
     * @pattern ^(?!\s).{1,1000}(?<!\s)$
     * @type string
    */
    description: ScalarsStr1000;
    /**
     * @description Must be a natural number
     * @type integer
    */
    roleId: ScalarsId;
    /**
     * @type string
    */
    enabledState: EnumsEnabledState;
    /**
     * @type string, date-time
    */
    createdAt: string;
    /**
     * @type string, date-time
    */
    updatedAt: string;
};