/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { UseMutationOptions, QueryClient } from "@tanstack/react-query";
import type { CreateJobPostingMutationRequest, CreateJobPostingMutationResponse } from "../../ts/CreateJobPosting.ts";
import { useMutation } from "@tanstack/react-query";

export const createJobPostingMutationKey = () => [{ url: '/jobPostings' }] as const

export type CreateJobPostingMutationKey = ReturnType<typeof createJobPostingMutationKey>

/**
 * @description createJobPosting
 * {@link /jobPostings}
 */
export async function createJobPosting(data: CreateJobPostingMutationRequest, config: Partial<RequestConfig<CreateJobPostingMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<CreateJobPostingMutationResponse, ResponseErrorConfig<Error>, CreateJobPostingMutationRequest>({ method : "POST", url : `/jobPostings`, data : requestData, ... requestConfig })  
  return res.data
}

/**
 * @description createJobPosting
 * {@link /jobPostings}
 */
export function useCreateJobPosting<TContext>(options: 
{
  mutation?: UseMutationOptions<CreateJobPostingMutationResponse, ResponseErrorConfig<Error>, {data: CreateJobPostingMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<CreateJobPostingMutationRequest>> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? createJobPostingMutationKey()

  return useMutation<CreateJobPostingMutationResponse, ResponseErrorConfig<Error>, {data: CreateJobPostingMutationRequest}, TContext>({
    mutationFn: async({ data }) => {
      return createJobPosting(data, config)
    },
    mutationKey,
    ...mutationOptions
  }, queryClient)
}