/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import type { ListJobPostingsQueryResponse, ListJobPostingsQueryParams } from "../../ts/ListJobPostings.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const listJobPostingsQueryKey = (params?: ListJobPostingsQueryParams) => [{ url: '/jobPostings' }, ...(params ? [params] : [])] as const

export type ListJobPostingsQueryKey = ReturnType<typeof listJobPostingsQueryKey>

/**
 * @description listJobPostings
 * {@link /jobPostings}
 */
export async function listJobPostings(params?: ListJobPostingsQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<ListJobPostingsQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : `/jobPostings`, params, ... requestConfig })  
  return res.data
}

export function listJobPostingsQueryOptions(params?: ListJobPostingsQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = listJobPostingsQueryKey(params)
  return queryOptions<ListJobPostingsQueryResponse, ResponseErrorConfig<Error>, ListJobPostingsQueryResponse, typeof queryKey>({
 
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return listJobPostings(params, config)
   },
  })
}

/**
 * @description listJobPostings
 * {@link /jobPostings}
 */
export function useListJobPostings<TData = ListJobPostingsQueryResponse, TQueryData = ListJobPostingsQueryResponse, TQueryKey extends QueryKey = ListJobPostingsQueryKey>(params?: ListJobPostingsQueryParams, options: 
{
  query?: Partial<QueryObserverOptions<ListJobPostingsQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? listJobPostingsQueryKey(params)

  const query = useQuery({
   ...listJobPostingsQueryOptions(params, config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}