/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { UseMutationOptions, QueryClient } from "@tanstack/react-query";
import type { ReplaceJobPostingMutationRequest, ReplaceJobPostingMutationResponse, ReplaceJobPostingPathParams } from "../../ts/ReplaceJobPosting.ts";
import { useMutation } from "@tanstack/react-query";

export const replaceJobPostingMutationKey = () => [{ url: '/jobPostings/:id' }] as const

export type ReplaceJobPostingMutationKey = ReturnType<typeof replaceJobPostingMutationKey>

/**
 * @description replaceJobPosting
 * {@link /jobPostings/:id}
 */
export async function replaceJobPosting(id: ReplaceJobPostingPathParams["id"], data: ReplaceJobPostingMutationRequest, config: Partial<RequestConfig<ReplaceJobPostingMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<ReplaceJobPostingMutationResponse, ResponseErrorConfig<Error>, ReplaceJobPostingMutationRequest>({ method : "PUT", url : `/jobPostings/${id}`, data : requestData, ... requestConfig })  
  return res.data
}

/**
 * @description replaceJobPosting
 * {@link /jobPostings/:id}
 */
export function useReplaceJobPosting<TContext>(options: 
{
  mutation?: UseMutationOptions<ReplaceJobPostingMutationResponse, ResponseErrorConfig<Error>, {id: ReplaceJobPostingPathParams["id"], data: ReplaceJobPostingMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<ReplaceJobPostingMutationRequest>> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? replaceJobPostingMutationKey()

  return useMutation<ReplaceJobPostingMutationResponse, ResponseErrorConfig<Error>, {id: ReplaceJobPostingPathParams["id"], data: ReplaceJobPostingMutationRequest}, TContext>({
    mutationFn: async({ id, data }) => {
      return replaceJobPosting(id, data, config)
    },
    mutationKey,
    ...mutationOptions
  }, queryClient)
}