/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export const uploadsUploadCategoryEnum = {
    "RESUMES": "RESUMES"
} as const;

export type UploadsUploadCategoryEnum = (typeof uploadsUploadCategoryEnum)[keyof typeof uploadsUploadCategoryEnum];

export type UploadsUploadCategory = UploadsUploadCategoryEnum;