/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ScalarsN } from "../scalars/N.ts";
import type { ScalarsStr100 } from "../scalars/Str100.ts";
import type { UploadsUploadCategory } from "./UploadCategory.ts";

export type UploadsUpload = {
    /**
     * @type string
    */
    contentType: string;
    /**
     * @type string
    */
    category: UploadsUploadCategory;
    /**
     * @pattern ^(?!\s).{1,100}(?<!\s)$
     * @type string
    */
    staticPath: ScalarsStr100;
    /**
     * @description File size in bytes
    */
    size: ScalarsN;
};