/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ScalarsStr10 } from "../scalars/Str10.ts";

export type StructsSearchInput = {
    /**
     * @pattern ^(?!\s).{1,10}(?<!\s)$
     * @type string | undefined
    */
    searchTerm?: ScalarsStr10;
};