/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import type { ListNotificationsQueryResponse, ListNotificationsQueryParams } from "../../ts/ListNotifications.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const listNotificationsSuspenseQueryKey = (params?: ListNotificationsQueryParams) => [{ url: '/notifications' }, ...(params ? [params] : [])] as const

export type ListNotificationsSuspenseQueryKey = ReturnType<typeof listNotificationsSuspenseQueryKey>

/**
 * @description listNotifications
 * {@link /notifications}
 */
export async function listNotificationsSuspense(params?: ListNotificationsQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<ListNotificationsQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : `/notifications`, params, ... requestConfig })  
  return res.data
}

export function listNotificationsSuspenseQueryOptions(params?: ListNotificationsQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = listNotificationsSuspenseQueryKey(params)
  return queryOptions<ListNotificationsQueryResponse, ResponseErrorConfig<Error>, ListNotificationsQueryResponse, typeof queryKey>({
 
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return listNotificationsSuspense(params, config)
   },
  })
}

/**
 * @description listNotifications
 * {@link /notifications}
 */
export function useListNotificationsSuspense<TData = ListNotificationsQueryResponse, TQueryKey extends QueryKey = ListNotificationsSuspenseQueryKey>(params?: ListNotificationsQueryParams, options: 
{
  query?: Partial<UseSuspenseQueryOptions<ListNotificationsQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? listNotificationsSuspenseQueryKey(params)

  const query = useSuspenseQuery({
   ...listNotificationsSuspenseQueryOptions(params, config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}