/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export const jobApplicationsGenderEnum = {
    "MALE": "MALE",
    "FEMALE": "FEMALE",
    "OTHER": "OTHER"
} as const;

export type JobApplicationsGenderEnum = (typeof jobApplicationsGenderEnum)[keyof typeof jobApplicationsGenderEnum];

export type JobApplicationsGender = JobApplicationsGenderEnum;