/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { JobApplicationsGender } from "./Gender.ts";
import type { JobApplicationsJobQualificationLevel } from "./JobQualificationLevel.ts";
import type { JobApplicationsProcessingState } from "./ProcessingState.ts";
import type { ScalarsDatetime } from "../scalars/Datetime.ts";
import type { ScalarsEmail } from "../scalars/Email.ts";
import type { ScalarsId } from "../scalars/Id.ts";
import type { ScalarsMobile } from "../scalars/Mobile.ts";
import type { ScalarsMoney } from "../scalars/Money.ts";
import type { ScalarsN } from "../scalars/N.ts";
import type { ScalarsStr15 } from "../scalars/Str15.ts";
import type { ScalarsStr50 } from "../scalars/Str50.ts";
import type { ScalarsStr100 } from "../scalars/Str100.ts";
import type { ScalarsStr200 } from "../scalars/Str200.ts";

/**
 * @description The template for omitting properties.
*/
export type JobApplicationsJobApplicationInput = {
    /**
     * @description Must be a natural number
     * @type integer
    */
    jobPostingId: ScalarsId;
    /**
     * @type string
    */
    firstName: string;
    /**
     * @type string
    */
    lastName: string;
    /**
     * @pattern ^(?!\s).{1,50}(?<!\s)$
     * @type string, email
    */
    email: ScalarsEmail;
    /**
     * @pattern ^(?!\s).{1,15}(?<!\s)$
     * @type string
    */
    nic: ScalarsStr15;
    /**
     * @pattern ^0\d{9}$
     * @type string
    */
    mobile: ScalarsMobile;
    /**
     * @pattern ^(?!\s).{1,100}(?<!\s)$
     * @type string
    */
    cvPath: ScalarsStr100;
    /**
     * @pattern ^(?!\s).{1,200}(?<!\s)$
     * @type string
    */
    address: ScalarsStr200;
    answerDob: (ScalarsDatetime | null);
    answerGender: (JobApplicationsGender | null);
    answerExperienceYears: (ScalarsN | null);
    answerQualificationLevel: (JobApplicationsJobQualificationLevel | null);
    answerPreferredLocation: (ScalarsStr50 | null);
    answerExpectedSalary: (ScalarsMoney | null);
    /**
     * @type string
    */
    processingState: JobApplicationsProcessingState;
    interview1At: (ScalarsDatetime | null);
    interview2At: (ScalarsDatetime | null);
    interview3At: (ScalarsDatetime | null);
    interview4At: (ScalarsDatetime | null);
    interview5At: (ScalarsDatetime | null);
    interview6At: (ScalarsDatetime | null);
    interview7At: (ScalarsDatetime | null);
    interview8At: (ScalarsDatetime | null);
    interview9At: (ScalarsDatetime | null);
    /**
     * @type string, date-time
    */
    createdAt: string;
    /**
     * @type string, date-time
    */
    updatedAt: string;
};