/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export const jobApplicationsJobQualificationLevelEnum = {
    "BACHELORS": "BACHELORS",
    "MASTERS": "MASTERS",
    "PHD": "PHD"
} as const;

export type JobApplicationsJobQualificationLevelEnum = (typeof jobApplicationsJobQualificationLevelEnum)[keyof typeof jobApplicationsJobQualificationLevelEnum];

export type JobApplicationsJobQualificationLevel = JobApplicationsJobQualificationLevelEnum;