/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export const jobApplicationsProcessingStateEnum = {
    "PENDING": "PENDING",
    "SHORTLISTED": "SHORTLISTED",
    "INTERVIEW_SCHEDULED": "INTERVIEW_SCHEDULED",
    "ACCEPTED": "ACCEPTED",
    "REJECTED": "REJECTED"
} as const;

export type JobApplicationsProcessingStateEnum = (typeof jobApplicationsProcessingStateEnum)[keyof typeof jobApplicationsProcessingStateEnum];

export type JobApplicationsProcessingState = JobApplicationsProcessingStateEnum;